--- #MASTER PLAYBOOK FOR WEB SERVERS
- hosts: apacheweb
  remote_user: test
  become: yes
  become_method: sudo
  connection: ssh
  pre_tasks:
  - name: When did the ROLE took to run
    raw: date > /home/test/startofrole.log
  roles: 
    - debian_webservers
  post_tasks:
  - name: When did the Role end
    raw: date > /home/test/endoforle.log
