- name: Install Apache Web Server
  yum: pkg={{ redhat_apache }} state=latest
  when: ansible_os_family == "RedHat"
- name: Wait for the service to start listening on port 80
  wait_for:
    port: 80
    state: started
  
