- name: Install Apache Web Server
  yum: pkg={{ redhat_apache }} state=latest
  when: ansible_os_family == "RedHat"
  ignore_errors: yes
  notify: Restart HTTPD
- name: Install (Debian/Ubuntu) Apache Web Server
  apt: pkg={{ debian_apache }} state=latest
  when: ansible_os_family == "Debian"
  notify: Restart Apache2
  ignore_errors: yes
